name: passwd
description: passwd new implementation

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  random_password_generator: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.1.0

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/images/load-background.png"
  adaptive_icon_foreground: "assets/images/load-foreground.png"

flutter:
  uses-material-design: true

# assets:
#   - images/a_dot_burr.jpeg

# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
